version: '3'
services:
  postgres-test:
    image: "ankane/pgvector:v0.5.1"
    container_name: "omnivore-postgres-test"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=omnivore_test
      - PG_POOL_MAX=20
    healthcheck:
      test: "exit 0"
      interval: 2s
      timeout: 12s
      retries: 3
    expose:
      - 5432

  migrate-test:
    build:
      context: .
      dockerfile: ./packages/db/Dockerfile
    container_name: "omnivore-migrate-test"
    command: '/bin/sh ./packages/db/setup.sh' # Also create a demo user with email: demo@omnivore.app, password: demo
    environment:
      - PGPASSWORD=postgres
      - PG_HOST=postgres-test
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=omnivore_test
    depends_on:
      postgres-test:
        condition: service_healthy

  api-test:
    build:
      context: .
      dockerfile: ./packages/api/Dockerfile-test
    container_name: "omnivore-api-test"
    environment:
      - API_ENV=local
      - PG_HOST=postgres-test
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=omnivore_test
      - PG_PORT=5432
      - PG_POOL_MAX=20
      - IMAGE_PROXY_SECRET=some-secret
      - JWT_SECRET=some_secret
      - SSO_JWT_SECRET=some_sso_secret
      - CLIENT_URL=http://localhost:3000
      - GATEWAY_URL=http://localhost:8080/api
      - CONTENT_FETCH_URL=http://localhost:9090/
      - BOOKMARKLET_JWT_SECRET=some_bookmarklet_secret
      - BOOKMARKLET_VERSION=1.0.0
      - PREVIEW_IMAGE_WRAPPER_ID='selected_highlight_wrapper'
      - GCP_PROJECT_ID=omnivore-local
      - GAUTH_CLIENT_ID='notset'
      - GAUTH_SECRET='notset'
      - SEGMENT_WRITE_KEY='test'
      - PUBSUB_VERIFICATION_TOKEN='123456'
    depends_on:
      migrate-test:
        condition: service_completed_successfully
