language: node_js
cache:
  npm: false
env:
  - HUSKY_SKIP_INSTALL=true
node_js:
  - 12
  - 16
script:
  - npm run lint
  - nyc --silent npm run test
  - nyc report --reporter=text-lcov | coveralls
  - nyc check-coverage --lines 30
after_success:
  - NODE_ENV=production npm run build
  - semantic-release --branches main
notifications:
  email: false
sudo: false
